preload = /home/bepp/wallpapers/minecraft_tricky_trials.png
preload = /home/bepp/wallpapers/Minecraft_Fall_Drop_Campaign_Key_Art_DotNet_Downloadable_Wallpaper_1920x1080.png
#if more than one preload is desired then continue to preload other backgrounds
# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper {
    monitor = eDP-1
    path=/home/bepp/wallpapers/Minecraft_Fall_Drop_Campaign_Key_Art_DotNet_Downloadable_Wallpaper_1920x1080.png
    fit_mode = cover
}

#if more than one monitor in use, can load a 2nd image
# .. more monitors

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
ipc = off


